CREATE TABLE vote (
    id SERIAL PRIMARY KEY,
    ip VARCHAR NOT NULL,
    voteBetween VARCHAR NOT NULL,
    vote VARCHAR NOT NULL
);

CREATE TABLE cat (
    id SERIAL PRIMARY KEY,
    link VARCHAR NOT NULL
);